export const data = [
    {
        id:1,
        name:'Broccoli',
        image:'https://www.health.harvard.edu/media/content/images/p7_Broccoli_HH1812_gi905351392.jpg',
        calories:34
    },
    {
        id:2,
        name:'Cauliflower',
        image:'http://t3.gstatic.com/images?q=tbn:ANd9GcSeg3atgP35f83U_eFhOPcnD6-ZDUh19g0EhYvLjznjfW4p6tzcSyr1qLHAEA7Q0zPZSJqjUuX-XhQA2aLcggM',
        calories:25
    },
    {
        id:3,
        name:'Nudels',
        image:'https://upload.wikimedia.org/wikipedia/commons/a/a8/Fresh_ramen_noodle_001.jpg',
        calories:138
    },
    {
        id:4,
        name:'Soy sauce',
        image:'https://cdn.shopify.com/s/files/1/0206/9470/products/10683_HFARM_49645309-3_grande.jpeg?v=1441105440',
        calories:12
    },
    {
        id:5,
        name:'Carrot',
        image:'https://befreshcorp.net/wp-content/uploads/2017/06/product-packshot-Carrot-558x600.jpg',
        calories:24
    },
    {
        id:6,
        name:'Carrot',
        image:'https://www.veggycation.com.au/siteassets/veggycationvegetable/onion.jpg',
        calories:10
    },
    {
        id:7,
        name:'Chicken',
        image:'https://www.skinnytaste.com/wp-content/uploads/2020/04/Crispy-Air-Fryer-Chicken-Tenders-4.jpg',
        calories:10
    }
]